-- Auto-generated by JNKIE Discord Bot
-- Service: Testing Service
-- Generated for: 1yajusaiko4545

getgenv().SCRIPT_KEY = "nile-c8163dca-4d21-4dc9-98af-7b09f268dceb"

loadstring(game:HttpGet("https://api.jnkie.com/api/v1/luascripts/public/0c237fdefab6050afef9e14c974903d107432c6eee626c0dceb9561b6cd7d3cc/download"))()
